resume: False
weight: ./checkpoints/instPIFu_0829/model_latest.pth
finetune: False
method: bgPIFu
exp_name: debug
phase: reconstruction
device:
  use_gpu: True
  gpu_ids: '6,7'
data:
  dataset: front3d_bg
  data_path: ./data/3dfront/prepare_data
  split_path: ./data/3dfront/bg_split
  occ_path: ./data/3dfront/bgocc
  batch_size: 12
  num_workers: 12
  use_aug: True
  rotate_degree: 2.5
  image_height: 200
  image_width: 268
  use_positional_embedding: True
  multires: 4
optimizer:
  type: Adam
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  eps:
  weight_decay:
scheduler:
  type: MultiStepLR
  milestone: [50,80]
  gamma: 0.2
model:
  mlp_dim: [1283, 1024, 512, 256, 128, 1]
  no_residual: False
  num_stack: 4
  norm: group
  hg_down: ave_pool
  num_hourglass: 2
  hourglass_dim: 256
  skip_hourglass: False
  multires: 4
  use_atten: True
other:
  nepoch: 100
  model_save_interval: 1
  model_save_dir: ./checkpoints
  visualize_interval: 1000
  dump_result: True
  dump_interval: 1000


